import type { Category, Group, Metrics, Offer } from "./types";

export const categories: Category[] = [
  { id: "cat-home", name: "Koti & energia", slug: "koti-energia", parent_id: null, icon: "⚡", country_code: "FI", active: true, regulated: true, sort_order: 1, participation_count: 1260 },
  { id: "cat-money", name: "Raha", slug: "raha", parent_id: null, icon: "🏦", country_code: "FI", active: true, regulated: true, sort_order: 2, participation_count: 144 },
  { id: "cat-contracts", name: "Sopimukset", slug: "sopimukset", parent_id: null, icon: "📱", country_code: "FI", active: true, regulated: true, sort_order: 3, participation_count: 380 },
  { id: "cat-mobility", name: "Liikkuminen", slug: "liikkuminen", parent_id: null, icon: "🚗", country_code: "FI", active: true, regulated: false, sort_order: 4, participation_count: 612 },
  { id: "cat-shopping", name: "Ostokset", slug: "ostokset", parent_id: null, icon: "🛒", country_code: "FI", active: true, regulated: false, sort_order: 5, participation_count: 499 },
  { id: "cat-travel", name: "Matkat", slug: "matkat", parent_id: null, icon: "🏨", country_code: "FI", active: true, regulated: true, sort_order: 6, participation_count: 238 }
];

export const groups: Group[] = [
  {
    id: "grp-samsung-tv",
    name: "TESTIDATA: Samsung 65 tuuman TV",
    slug: "testidata-samsung-65-tv",
    category_id: "cat-shopping",
    category_name: "Ostokset",
    category_slug: "ostokset",
    category_icon: "🛒",
    description: "Samsung 65\" tarkka testimalli. Fyysinen tuote, jossa kokonaishinta sisältää toimituksen.",
    terms: ["TESTIDATA - ei oikea tarjous.", "Malli: Samsung QE65Q70D demo.", "Toimitus lisätään kokonaishintaan.", "Pelkkä Joukkoon liittyminen ei muodosta ostositoumusta."],
    area: "Valtakunnallinen",
    target_count: 500,
    follower_count: 720,
    member_count: 499,
    committed_count: 499,
    ready_now_count: 462,
    offer_count: 1,
    status: "active",
    featured: true,
    country_code: "FI",
    currency_code: "EUR",
    locale: "fi-FI",
    timezone: "Europe/Helsinki",
    next_tier_label: "1 osallistuja seuraavaan portaaseen: 500 hyväksyjää = 499 €",
    created_at: "2026-08-22T00:00:00Z"
  },
  {
    id: "grp-electricity",
    name: "TESTIDATA: Sähkösopimus 12 kk",
    slug: "testidata-sahkosopimus-12kk",
    category_id: "cat-home",
    category_name: "Koti & energia",
    category_slug: "koti-energia",
    category_icon: "⚡",
    description: "Määräaikaisia ja heti vaihtavia testikäyttäjiä. Sopimus syntyy vasta erillisellä tarjouksen hyväksynnällä.",
    terms: ["TESTIDATA - ei oikea sopimus.", "Osa käyttäjistä voi vaihtaa heti, osa vasta määräajan päättyessä.", "LEGAL_REVIEW_REQUIRED energia- ja etämyyntisäännöille.", "Yrityksille näytetään vain aggregoidut päättymisjakaumat."],
    area: "Suomi",
    target_count: 1000,
    follower_count: 1260,
    member_count: 1000,
    committed_count: 1000,
    ready_now_count: 410,
    offer_count: 1,
    status: "active",
    featured: true,
    country_code: "FI",
    currency_code: "EUR",
    locale: "fi-FI",
    timezone: "Europe/Helsinki",
    next_tier_label: "Seuraava tarjousporras 2 000 hyväksyjää = 439 €",
    created_at: "2026-08-21T00:00:00Z"
  },
  {
    id: "grp-hotel",
    name: "TESTIDATA: Hotelliyöpyminen Tampereella",
    slug: "testidata-hotelliyopyminen-tampere",
    category_id: "cat-travel",
    category_name: "Matkat",
    category_slug: "matkat",
    category_icon: "🏨",
    description: "Hotelliyöpyminen 14.-15.11.2026 kahdelle hengelle, aamiainen mukana, peruutusehdot näkyvissä.",
    terms: ["TESTIDATA - ei oikea varaus.", "Päivämäärät 14.-15.11.2026.", "Huonetyyppi: standard kahdelle.", "LEGAL_REVIEW_REQUIRED majoitus- ja matkapakettirajaukseen."],
    area: "Tampere",
    target_count: 200,
    follower_count: 238,
    member_count: 188,
    committed_count: 160,
    ready_now_count: 144,
    offer_count: 1,
    status: "active",
    featured: false,
    country_code: "FI",
    currency_code: "EUR",
    locale: "fi-FI",
    timezone: "Europe/Helsinki",
    next_tier_label: "12 hyväksyjää seuraavaan portaaseen",
    created_at: "2026-08-20T00:00:00Z"
  },
  {
    id: "grp-tyres",
    name: "TESTIDATA: Talvirenkaat 205/55 R16",
    slug: "testidata-talvirenkaat-205-55-r16",
    category_id: "cat-mobility",
    category_name: "Liikkuminen",
    category_slug: "liikkuminen",
    category_icon: "🚗",
    description: "Valtakunnallinen rengasjoukko, jossa toimitus veloitetaan erikseen ja näytetään kokonaishinnassa.",
    terms: ["TESTIDATA - ei oikea tilaus.", "Tuote: 4 kpl 205/55 R16 kitkarenkaita.", "Toimitus 39 € sisältyy kuluttajalle näytettävään kokonaishintaan.", "Asennus ei sisälly hintaan."],
    area: "Valtakunnallinen",
    target_count: 300,
    follower_count: 612,
    member_count: 305,
    committed_count: 300,
    ready_now_count: 286,
    offer_count: 1,
    status: "active",
    featured: false,
    country_code: "FI",
    currency_code: "EUR",
    locale: "fi-FI",
    timezone: "Europe/Helsinki",
    next_tier_label: "Seuraava tarjousporras 600 hyväksyjää",
    created_at: "2026-08-19T00:00:00Z"
  }
];

export const offers: Offer[] = [
  {
    id: "offer-tv-demo",
    group_id: "grp-samsung-tv",
    version: 1,
    company_name: "Testi Elektroniikka Oy",
    company_verification_status: "unverified",
    company_business_id: "0000000-0",
    company_contact: "testi@example.invalid",
    company_country: "FI",
    title: "TESTIDATA: Samsung QE65Q70D toimitettuna",
    product_or_service: "Samsung QE65Q70D 65\" TV",
    description: "Hinta laskee portaissa. 499 osallistujaa on yhden päässä ensimmäisestä toteutusportaasta.",
    price: 459,
    mandatory_fees: 0,
    normal_price: 599,
    estimated_saving: 100,
    delivery_price: 40,
    delivery_method: "Kotiinkuljetus Suomessa",
    total_price: 499,
    minimum_participants: 500,
    contract_length: null,
    vat_status: "Sisältää ALV:n",
    delivery_time: "5-10 arkipäivää toteutuneesta Joukosta",
    terms: "TESTIDATA. Myyjä vastaa tuotteesta, toimituksesta, takuusta ja palautusehdoista.",
    terms_type: "text",
    terms_text: "Testi Elektroniikka Oy:n demo-myyntiehdot. Tuotteen takuu 24 kk. Palautus vain myyjän ehtojen mukaisesti.",
    terms_url: null,
    terms_document_reference: null,
    terms_version: "test-tv-v1",
    accepted_by_company_at: "2026-08-22T00:00:00Z",
    starts_at: "2026-08-22T00:00:00Z",
    valid_until: "2026-12-31",
    tiers: [
      { min_acceptances: 500, price: 499, label: "500 hyväksyjää = 499 € toimitettuna" },
      { min_acceptances: 1000, price: 469, label: "1000 hyväksyjää = 469 € toimitettuna" },
      { min_acceptances: 2000, price: 439, label: "2000 hyväksyjää = 439 € toimitettuna" }
    ],
    locked_at: null,
    published_at: "2026-08-22T00:00:00Z",
    response_status: "pending"
  },
  {
    id: "offer-electricity-demo",
    group_id: "grp-electricity",
    version: 1,
    company_name: "Demo Energia Oy",
    company_verification_status: "unverified",
    company_business_id: "0000000-0",
    company_contact: "testi@example.invalid",
    company_country: "FI",
    title: "TESTIDATA: JOUKKO-sähkö 12 kk",
    product_or_service: "Sähkösopimus 12 kk",
    description: "Demo-tarjous, jossa hinta paranee hyväksyvien käyttäjien määrän kasvaessa.",
    price: 469,
    mandatory_fees: 0,
    normal_price: 549,
    estimated_saving: 80,
    delivery_price: 0,
    delivery_method: "Sähköinen sopimus",
    total_price: 469,
    minimum_participants: 500,
    contract_length: "12 kk",
    vat_status: "Sisältää ALV:n",
    delivery_time: "Sopimuksen aloitus käyttäjän nykyisen sopimuksen salliessa",
    terms: "TESTIDATA. LEGAL_REVIEW_REQUIRED ennen tuotantoa.",
    terms_type: "text",
    terms_text: "Demo Energia Oy vastaa myyjänä tarjouksen ehdoista, toimituksesta ja kuluttajansuojatiedoista.",
    terms_url: null,
    terms_document_reference: null,
    terms_version: "test-energy-v1",
    accepted_by_company_at: "2026-08-22T00:00:00Z",
    starts_at: "2026-08-22T00:00:00Z",
    valid_until: "2026-12-31",
    tiers: [
      { min_acceptances: 500, price: 499, label: "500 hyväksyjää = 499 €" },
      { min_acceptances: 1000, price: 469, label: "1000 hyväksyjää = 469 €" },
      { min_acceptances: 2000, price: 439, label: "2000 hyväksyjää = 439 €" }
    ],
    locked_at: null,
    published_at: "2026-08-22T00:00:00Z",
    response_status: "pending"
  },
  {
    id: "offer-hotel-demo",
    group_id: "grp-hotel",
    version: 1,
    company_name: "Demo Hotelli Oy",
    company_verification_status: "unverified",
    company_business_id: "0000000-0",
    company_contact: "testi@example.invalid",
    company_country: "FI",
    title: "TESTIDATA: Tampere 1 yö kahdelle",
    product_or_service: "Standard-huone kahdelle 14.-15.11.2026",
    description: "Aamiainen mukana. Peruutusehdot ovat myyjän omissa ehdoissa.",
    price: 129,
    mandatory_fees: 0,
    normal_price: 169,
    estimated_saving: 40,
    delivery_price: 0,
    delivery_method: "Varauskoodi sähköpostilla",
    total_price: 129,
    minimum_participants: 200,
    contract_length: "1 yö",
    vat_status: "Sisältää ALV:n",
    delivery_time: "Varausvahvistus 2 arkipäivän sisällä toteutumisesta",
    terms: "TESTIDATA. Majoittaja vastaa varauksesta ja peruutusehdoista.",
    terms_type: "text",
    terms_text: "Demo Hotelli Oy:n testiehdot. Maksuton peruutus 7 vrk ennen saapumista.",
    terms_url: null,
    terms_document_reference: null,
    terms_version: "test-hotel-v1",
    accepted_by_company_at: "2026-08-22T00:00:00Z",
    starts_at: "2026-08-22T00:00:00Z",
    valid_until: "2026-10-31",
    tiers: [
      { min_acceptances: 100, price: 139, label: "100 hyväksyjää = 139 €" },
      { min_acceptances: 200, price: 129, label: "200 hyväksyjää = 129 €" },
      { min_acceptances: 400, price: 119, label: "400 hyväksyjää = 119 €" }
    ],
    locked_at: null,
    published_at: "2026-08-22T00:00:00Z",
    response_status: "pending"
  },
  {
    id: "offer-tyres-demo",
    group_id: "grp-tyres",
    version: 1,
    company_name: "Demo Rengas Oy",
    company_verification_status: "unverified",
    company_business_id: "0000000-0",
    company_contact: "testi@example.invalid",
    company_country: "FI",
    title: "TESTIDATA: 4 kpl 205/55 R16 toimitettuna",
    product_or_service: "4 kpl 205/55 R16 kitkarenkaita",
    description: "Fyysinen valtakunnallinen tuote. Toimitus sisältyy kokonaishintaan, asennus ei sisälly.",
    price: 320,
    mandatory_fees: 0,
    normal_price: 399,
    estimated_saving: 40,
    delivery_price: 39,
    delivery_method: "Toimitus lähimpään noutopisteeseen",
    total_price: 359,
    minimum_participants: 300,
    contract_length: null,
    vat_status: "Sisältää ALV:n",
    delivery_time: "7-14 arkipäivää",
    terms: "TESTIDATA. Myyjä vastaa tuotteen sopivuudesta, takuusta ja toimituksesta.",
    terms_type: "text",
    terms_text: "Demo Rengas Oy:n testiehdot. Ostaja tarkistaa rengaskoon ennen hyväksyntää.",
    terms_url: null,
    terms_document_reference: null,
    terms_version: "test-tyres-v1",
    accepted_by_company_at: "2026-08-22T00:00:00Z",
    starts_at: "2026-08-22T00:00:00Z",
    valid_until: "2026-11-15",
    tiers: [
      { min_acceptances: 300, price: 359, label: "300 hyväksyjää = 359 € toimitettuna" },
      { min_acceptances: 600, price: 339, label: "600 hyväksyjää = 339 € toimitettuna" },
      { min_acceptances: 1000, price: 319, label: "1000 hyväksyjää = 319 € toimitettuna" }
    ],
    locked_at: null,
    published_at: "2026-08-22T00:00:00Z",
    response_status: "pending"
  }
];

export const metrics: Metrics = {
  uniqueUsers: 2785,
  activeParticipations: 1992
};
