import type { LegalDocument } from "./types";

export const legalDocuments: Record<LegalDocument["slug"], LegalDocument> = {
  kayttoehdot: {
    slug: "kayttoehdot",
    title: "Käyttöehdot",
    version: "0.3.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-09-24",
    sections: [
      ["Palvelun tarkoitus", "JOUKKO kokoaa kuluttajien kiinnostusta, liittymisiä ja ehdollisia sitoumuksia ostovoimaksi."],
      ["Palveluntarjoaja", "Palveluntarjoajan viralliset tiedot lisätään ennen tuotantojulkaisua. LEGAL_REVIEW_REQUIRED"],
      ["Rekisteröityminen", "Käyttäjä luo tilin Supabase Auth -kirjautumisella. Rekisteröinnissä tallennetaan hyväksytty ehtoversio."],
      ["Käyttäjätili", "Käyttäjä vastaa antamiensa tietojen oikeellisuudesta."],
      ["Joukkoon liittyminen", "Liittyminen kasvattaa kiinnostuneiden määrää mutta ei yksin muodosta ostovelvoitetta."],
      ["Joukon perustaminen", "Aloittajan pitää kuvata tarve riittävän täsmällisesti. Olennaisia ehtoja ei saa muuttaa yksipuolisesti muiden liityttyä."],
      ["Ehdollinen sitoutuminen", "Käyttäjä voi sitoutua ehdoilla. Hyväksytyt ehdot tallennetaan muuttumattomana historiatietona."],
      ["Tarjousten ehdollinen kiinnostus", "JOUKKOssa kuluttaja voi testissä ilmaista ehdollisen kiinnostuksensa tiettyyn tarjoukseen, mutta se ei synnytä tilaus-, sopimus- tai maksuvelvollisuutta. Sitova mahdollinen sopimus tehdään erikseen tunnistetun myyjän omassa ostoprosessissa. LEGAL_REVIEW_REQUIRED"],
      ["Ennakkotiedot ennen hyväksyntää", "Ennen sitovaa hyväksyntää näytetään myyjän tunnistetiedot, tarjouksen olennaiset ominaisuudet, kokonaishinta veroineen ja pakollisine kuluineen, toimitus- tai toteutustapa ja -aika, voimassaolo, kesto, irtisanomis- ja peruuttamisehdot sekä reklamaatio- ja virhevastuutiedot."],
      ["Maksuvelvollisuudesta kertova toiminto", "Jos hyväksyntä synnyttää maksuvelvollisuuden, painikkeen ja välittömän näkymän on ilmaistava se yksiselitteisesti. Pelkkää kiinnostuksen tai Minä myös -ilmaisua ei esitetä ostona."],
      ["Ehdollisen kiinnostuksen tekninen merkintä", "Tietokannan sisäinen deal-merkintä tarkoittaa vain ehdollista kiinnostusta, kunnes myyjän kanssa on myöhemmin tosiasiallisesti tehty lopullinen sopimus. Kilpailun voittajan valinta ei ole tilausvahvistus eikä aiheuta maksuvelvoitetta."],
      ["Tietojen luovutus myyjälle", "Ennen hyväksyntää käyttäjälle näytetään, että kaupan toteuttamiseen tarvittavia vähimmäistietoja voidaan luovuttaa juuri kyseiselle yritykselle. Oikeusperuste ja tietoluokat tarkistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Toimitus ja toteutus", "Ennen hyväksyntää käyttäjälle näytetään tarjouksen päättymisaika ja myyjän ilmoittama arvioitu toimitus- tai toteutusaika."],
      ["Sopimuksen syntyminen", "JOUKON suunnitellussa mallissa sitova tilaus syntyy vasta ostajan nimenomaisella hyväksynnällä suoraan tunnistetun myyjäyrityksen kanssa. Myyjä antaa lain mukaiset ennakkotiedot, myyntiehdot ja oman vahvistuksensa. Alustan mahdollinen välittäjävastuu ja tekninen luovutustapa vahvistetaan ennen live-julkaisua. LEGAL_REVIEW_REQUIRED"],
      ["Määräaikaiset sopimukset", "JOUKKO ei saa aiheuttaa sopimusrikettä käyttäjän puolesta."],
      ["Peruuttaminen ja kuluttajansuoja", "Kuluttajansuojan ja peruuttamisoikeuden yksityiskohdat tarkistetaan ennen julkaisua. LEGAL_REVIEW_REQUIRED"],
      ["Peruuttamistoiminto", "Kun lainsäädäntö sitä edellyttää, palvelussa tarjotaan helposti löydettävä sähköinen peruuttamistoiminto ja peruuttamisesta annetaan vahvistus pysyvällä tavalla. Myyjä ilmoittaa ennen sopimusta 14 päivän peruuttamisoikeuden tai soveltuvan lakisääteisen poikkeuksen ja sen perusteen. LEGAL_REVIEW_REQUIRED"],
      ["Myyjän tilaus- ja sopimusvahvistus", "Lopullisen sopimuksen tehnyt myyjä toimittaa asiakkaalle lain mukaisen pysyvän tilaus- tai sopimusvahvistuksen, jossa ovat hänen viralliset tietonsa, ehdot, hinta ja toimitus. JOUKON sisäinen kiinnostus- tai kilpailuviesti ei korvaa myyjän vahvistusta. LEGAL_REVIEW_REQUIRED"],
      ["Yrityksen ja kuluttajan välinen sopimus", "JOUKKO toimii alustana/välittäjänä määriteltävässä roolissa. LEGAL_REVIEW_REQUIRED"],
      ["Sopimusosapuolet ja vastuunjako", "Tavoiteltu malli: ostaja ostaa tuotteen tai palvelun tarjouksen tehneeltä tunnistetulta yritykseltä tämän omissa nimissä ja lukuun. Myyjä vastaa oman tarjouksensa mukaisesta toimituksesta, asennuksesta, maksujen vastaanottamisesta, lakisääteisestä virhevastuusta, takuusta, peruuttamisesta ja reklamaatioiden käsittelystä. Ennen mahdollista sitovaa vaihetta ilmoitetaan myyjän virallinen nimi ja yhteystiedot sekä se, että myyjä eikä JOUKKO on kauppasopimuksen toinen osapuoli. LEGAL_REVIEW_REQUIRED"],
      ["JOUKON oma vastuu", "JOUKKO tarjoaa kysynnänkeruu-, esittely- ja vertailupalvelun sekä vastaa aina omasta alustatoiminnastaan, käyttäjätiedoista ja soveltuvista lakisääteisistä velvoitteistaan. Vastuusta, jota laki ei salli rajata pois, ei voida sopimusehdoilla vapautua. Kunkin palvelutyypin välittäjävastuun poikkeukset selvitetään ennen sitovan kaupankäynnin aktivointia. LEGAL_REVIEW_REQUIRED"],
      ["Maksujen kulku", "JOUKKO ei ota ostajan kauppahintaa eikä vastaanota käsirahaa tai varausta. Ostaja maksaa myyjäyritykselle myyjän turvallisessa ostoprosessissa. JOUKKO laskuttaa erillisen etukäteen hyväksytyn onnistumispalkkion myyjäyritykseltä vasta todistetusti toteutuneesta kaupasta sovittujen ehtojen mukaisesti. Live-maksut eivät ole käytössä testissä."],
      ["Yhteisostokampanjan tarkka tuote", "Joukolla tulee olla vertailukelpoinen vähimmäispaketti ja rajaukset; eri toimitussisällöt, rahoitus, liittymäsopimukset tai valinnaiset palvelut vertaillaan erikseen. Myyjien kokonaishinnat sisältävät kaikki ostajalle pakolliset kulut."],
      ["Kilpailun aikarajat", "Kiinnostuksen keruu, yritysten tarjousaika ja ostajan oma hyväksymisaika kerrotaan kampanjan ja tarjouksen yhteydessä. Jos tarjous tai kampanja vanhenee, käyttäjä ei sitoudu automaattisesti eikä määräaikaista sopimusta vaihdeta hänen puolestaan."],
      ["Ei säästö- eikä sopimustakuuta", "JOUKKO ei lupaa, että ostoryhmälle löytyy yritystarjous, tarjous on markkinoiden halvin tai myyjä voi toimittaa joka kohteeseen. Mahdolliset säästöväitteet perustellaan todellisilla vertailutiedoilla."],
      ["Myyjän vastuu", "Myyjä määrittelee omat myyntiehtonsa ja vastaa tuotteesta, palvelusta, toimituksesta, reklamaatioista, takuista ja kuluttajansuojan pakollisista tiedoista oman roolinsa mukaisesti."],
      ["JOUKON asema", "Alustan asema välittäjänä tai markkinapaikkana täsmennetään juridisessa tarkistuksessa."],
      ["Kielletty käyttö", "Laiton sisältö, harhaanjohtavat tarjouspyynnöt ja henkilötietojen julkaisu julkiseen kuvaukseen on kielletty."],
      ["Sisällön moderointi", "Admin voi hyväksyä, piilottaa, keskeyttää tai jäädyttää Joukon."],
      ["Ilmoitus laittomasta sisällöstä ja muutoksenhaku", "Käyttäjälle tarjotaan yhteydenottokanava epäillyn laittoman tai ehtojen vastaisen sisällön ilmoittamiseen. Moderointipäätös perustellaan ja käytettävissä oleva oikaisu- tai valitusmenettely ilmoitetaan sovellettavan lain mukaan. LEGAL_REVIEW_REQUIRED"],
      ["Järjestys ja vertailu", "Vertailun ja tarjousten järjestämisen tärkeimmät perusteet, kuten kokonaishinta, ehdot, toimitusaika ja saavutettu hintaporras, kerrotaan käyttäjälle. Maksettu näkyvyys merkitään eikä sitä esitetä puolueettomana paremmuusjärjestyksenä."],
      ["Ikä ja oikeustoimikelpoisuus", "Sitovan hyväksynnän tekijällä on oltava siihen vaadittava oikeustoimikelpoisuus ja valtuus. Alaikäisiä tai säänneltyjä tuoteryhmiä koskevat rajat toteutetaan ennen niiden avaamista."],
      ["Vastuunrajoitukset", "Vastuunrajoitukset tehdään vain lain sallimissa rajoissa. LEGAL_REVIEW_REQUIRED"],
      ["Muutokset palveluun", "Palvelua voidaan kehittää ilman, että hyväksyttyä tarjoushistoriaa ylikirjoitetaan."],
      ["Ehtojen muutokset", "Uusi versio julkaistaan versionumerolla ja hyväksyntä tallennetaan tarvittaessa."],
      ["Sovellettava laki", "Sovellettava laki tarkennetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Yhteystiedot", "Yhteystiedot lisätään ennen tuotantojulkaisua."]
    ].map(([title, body]) => ({ title, body }))
  },
  yritysehdot: {
    slug: "yritysehdot",
    title: "Yritysehdot",
    version: "0.3.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-09-24",
    sections: [
      ["Yritystilin avaaminen", "Yritys avaa tilin ja ilmoittaa perustiedot."],
      ["Varmentaminen", "Yrityksen henkilöllisyys ja edustusoikeus varmennetaan ennen oikeita kaupallisia tarjouksia."],
      ["Elinkeinonharjoittajan jäljitettävyys", "Yritys antaa ennen tarjoamista virallisen nimensä, osoitteensa, puhelinnumeronsa, sähköpostinsa, kauppa- tai muun rekisterin ja rekisterinumeron, soveltuvan tunnisteen, maksutilin tiedot sekä vakuutuksen EU-sääntöjen mukaisuudesta. JOUKKO voi estää tarjoamisen, kunnes tiedot on varmennettu. LEGAL_REVIEW_REQUIRED"],
      ["Tarjouksen tekeminen", "Tarjous sisältää tuotteen/palvelun, hinnan, pakolliset lisäkulut, toimituksen, minimimäärän ja ehdot."],
      ["Luonnoksen poistaminen", "Yritys voi poistaa kokonaan vain luonnoksen, jolla ei ole seuraajia, kiinnostuneita, hyväksyntöjä, dealeja tai muuta käyttäjäinteraktiota."],
      ["Hintaportaat", "Yritys voi määrittää useita portaita, jotka lukitaan saavutettaessa."],
      ["Voimassaolo ja sulkeutuminen", "Tarjouksella on voimassaoloaika, mahdollinen hyväksyjä-/kapasiteettiraja ja sulkeutumisen jälkeen jo hyväksyneet käsitellään loppuun."],
      ["Toimitus-/toteutusaika", "Yritys ilmoittaa milloin toimitus tai palvelu toteutetaan tarjouksen päättymisen jälkeen. Toimitusaika kuuluu lukittuihin tarjousversion olennaisiin ehtoihin."],
      ["Yrityksen sitoutuminen", "Julkaistu tarjousversio lukitsee olennaiset ehdot kuluttajien sitoumusten jälkeen."],
      ["Tarjouksen muuttaminen", "Olennaiset heikennykset tehdään uutena tarjousversiona, ei ylikirjoituksena."],
      ["Tarjousversiot", "Versio, julkaisuhetki, hinnat, ehdot ja hyväksynnät tallennetaan audit-historiaan."],
      ["Myyjän omat ehdot", "Yritys antaa ehdot tekstinä, linkkinä tai dokumenttiviitteenä. JOUKKO ei laadi lopullisia myyntiehtoja yrityksen puolesta."],
      ["Kuluttajan ennakkotiedot", "Yritys vastaa tavaran tai palvelun ominaisuuksien, kokonaishinnan, verojen, lisäkulujen, toimituksen, sopimuksen keston, päättämisen, peruuttamisoikeuden tai sen poikkeuksen, reklamaatiokanavan, lakisääteisen virhevastuun ja mahdollisen takuun oikeellisuudesta."],
      ["Tuoteturvallisuus ja takaisinvedot", "Yritys antaa soveltuvat valmistaja-, vastuuhenkilö-, tunniste-, varoitus- ja turvallisuustiedot, ylläpitää niitä sekä ilmoittaa viipymättä vaarasta, takaisinvedosta tai viranomaismääräyksestä. Säännelty tuoteryhmä voidaan estää ilman erillistä hyväksyntää."],
      ["Toteutuneet asiakkaat", "Yritys saa vain oman tarjouksensa hyväksyneiden kaupan toteuttamiseen tarvittavat vähimmäistiedot. Käsittely ja tietojen luovutus vaatii oikeusperusteen. LEGAL_REVIEW_REQUIRED"],
      ["Poikkeuskeskeytys", "Hyväksyntöjen jälkeen yritys ei voi yksipuolisesti perua tarjousta. Poikkeuskeskeytys vaatii perusteen, vaikutusten kuvauksen ja admin-tarkistuksen. LEGAL_REVIEW_REQUIRED"],
      ["Yrityksen sopimuskumppanuus ja edustusoikeus", "Tarjouksen tehnyt todennettu yritys myy tuotteen tai palvelun omissa nimissään suoraan ostajalle. Yrityksen puolesta toimiva myyjä vakuuttaa edustusoikeutensa ja myyntialueen tai kanavarajoitusten noudattamisen. JOUKKO voi edellyttää valmistajan, maahantuojan, operaattorin tai muun päämiehen erillistä hyväksyntää."],
      ["Myyjän kauppa- ja toimitusvastuu", "Myyjä vastaa tarjoamansa tuotteen tai urakan täsmällisestä kuvauksesta, oikeasta kokonaishinnasta, tuoteturvallisuudesta, lain edellyttämistä pätevyyksistä ja luvista, toimituksesta, asennuksesta, takuun ehdoista, lakisääteisestä virhevastuusta, reklamaatioista ja soveltuvasta peruuttamisoikeudesta. Myyjä antaa tiedot ja hoitaa sopimuksensa suoraan ostajan kanssa."],
      ["Erikseen yksilöity kilpailupaketti", "Myyjä sitoutuu vastaamaan Joukon julkaistuihin pakollisiin vähimmäisominaisuuksiin ja kertoo kaikki poikkeamat ennen tarjousvertailua. Autossa määritellään tarkka malli ja varusteet; puhelinlaitteessa mallikoodi ja muisti; talopaketissa toimitusaste, sisältyvät työt, LVIS-rajaukset, lupa-, tontti- ja maanrakennuskustannusten rajaus. Pakolliset kulut on näytettävä ostajalle."],
      ["Sopimuskohtainen onnistumispalkkio ilman automaattista euromääräistä kattoa", "JOUKON ehdotushinnasto on tuotetyyppikohtainen: renkaille 4 %, puhelinlaitteille 3 %, asennuspaketeille 3 %, autoille 1 % ja talopaketeille 0,75 % toteutuneesta arvonlisäverottomasta sovitun toimitussisällön kauppahinnasta. Liittymille ehdotus 25 € ja laajakaistalle 35 € uudesta aktivoidusta sopimuksesta; ruokakorille 1 € vähintään 50 € tilauksesta. Kukin oikea prosentti tai euromäärä sekä täsmällinen laskentapohja vahvistetaan yrityksen kanssa kirjallisesti ennen tarjouksen julkaisua. Ehdot ovat alustava hinnasto, eivät voimassa oleva sitoumus. Provisiosta laskutetaan soveltuva arvonlisävero. LEGAL_REVIEW_REQUIRED"],
      ["Palkkion synty ja todentaminen", "Kiinnostuksenilmaisu, klikkaus, pelkkä tarjous tai vahvistamaton ostoaie ei synnytä palkkiota. Myyjä ilmoittaa toteutuneen sopimuksen ja todellisen verottoman sopimushinnan sekä toimittaa sovitun varmennustiedon. JOUKKO tarkistaa kaupan toteutumisen ja huomioi peruutukset, hyvitykset, petokset ja sovellettavan peruuttamisajan ennen palkkion lopullista laskutusta. Jos kauppa purkautuu kokonaan, palkkiota ei lopulta synny; osittaisen hyvityksen vaikutus määritetään ennen julkaisua."],
      ["Ei automaattista palkkiokattoa tai salattua muutosta", "Suurten kauppojen palkkio ei lopu automaattisesti 300 euroon. Tarjousversioon tallennetaan juuri kyseisen Joukon yrityksen hyväksymä palkkioperuste, prosentti ja ehtoversio, joita ei saa muuttaa jälkikäteen jo hyväksytyissä kaupoissa. Mahdollinen yrityskohtainen erikoishinta sovitaan ennen kampanjaan osallistumista eikä sitä sovelleta takautuvasti."],
      ["Maksuliikenne ja mahdollinen takaisinperintä", "Ostaja maksaa yksinomaan myyjälle. JOUKKO ei ota vastaan koko kauppahintaa eikä anna luottoa tai käsittele ostajan käsirahaa. Yritykselle laskutettava palkkio erääntyy sovitun varmennuksen ja palautus-/peruutusehtojen jälkeen. Erääntyneen palkkion hyvitys, palautus ja perintä kuvataan erillisissä yrityksen hyväksymissä laskutusehdoissa."],
      ["Alustan lakisääteiset velvoitteet", "JOUKKO vastaa omista alusta- ja tietosuojavelvoitteistaan. Myyjä vastaa oman kauppasopimuksensa suorituksesta, mutta pakottavan lain mukaisia alustan tai välittäjän velvoitteita ei voida mitätöidä näillä ehdoilla. Vastuunrajoitukset vahvistetaan asiantuntijatarkistuksessa ennen julkaisua. LEGAL_REVIEW_REQUIRED"],
      ["Alustan palkkiot", "Ennen tarjouksen lähettämistä yritykselle näytetään valitun kategorian palkkioperuste, prosentti tai euromäärä, verokohtelu, laskentaesimerkki ja palkkion syntyhetki. Yritys hyväksyy täsmälleen tämän version. Completed deal synnyttää vain hyväksytyn version mukaisen palkkion."],
      ["Peruuttaminen ja vahvistukset", "Yritys toimittaa JOUKKOlle peruuttamisohjeet ja poikkeusperusteen sekä käsittelee sähköisen peruuttamisen. Tilaus-, sopimus- ja peruuttamisvahvistukset toimitetaan kuluttajalle pysyvällä tavalla lain edellyttämässä ajassa. LEGAL_REVIEW_REQUIRED"],
      ["Laskutus", "Commissionit voidaan koota viikko-, kuukausi- tai kampanjakohtaiseksi laskutukseksi. Live-Stripeä ei käytetä ilman erillistä hyväksyntää."],
      ["Kielletty toiminta", "Tekaistut tarjoukset, väärät hinnat ja harhaanjohtavat edut on kielletty."],
      ["Harhaanjohtavat hinnat", "Alennusprosentti vaatii luotettavan vertailuhinnan."],
      ["Keinotekoiset alennukset", "JOUKKO vertaa ensisijaisesti todellista kokonaishintaa."],
      ["Asiakastietojen käyttö", "Yritys ei näe yksittäisiä henkilötietoja ennen asianmukaista hyväksyntää ja saa käyttää tietoja vain sallittuun toteutustarkoitukseen."],
      ["Tietosuoja", "Yritys sitoutuu käsittelemään tietoja sovellettavan lain mukaan."],
      ["Tietojen käyttötarkoitus ja turvallisuus", "Yritys käyttää luovutettuja tietoja vain kyseisen kaupan toteuttamiseen, rajaa käyttöoikeudet, suojaa tiedot, ilmoittaa tietoturvaloukkauksista ja poistaa tai palauttaa tiedot, kun käsittelyperuste päättyy, jollei laki vaadi säilyttämistä."],
      ["Tarjousten keskeyttäminen", "Keskeytys säilyttää historian ja vaatii syyn."],
      ["Yritystilin jäädyttäminen", "Admin voi jäädyttää tilin väärinkäytöksissä."],
      ["Vastuut", "Vastuut täsmennetään juridisesti. LEGAL_REVIEW_REQUIRED"],
      ["Riidat ja laki", "Riidat ja sovellettava laki tarkistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"]
    ].map(([title, body]) => ({ title, body }))
  },
  tietosuoja: {
    slug: "tietosuoja",
    title: "Tietosuojaseloste",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["Rekisterinpitäjä", "Lisätään ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Kerättävät tiedot", "Tilitiedot, Joukkotiedot, sopimuksen päättymistiedot, postinumero, yritystiedot, tarjoushistoria, lokit ja tekniset tiedot."],
      ["Käsittelyn tarkoitus", "Palvelun tarjoaminen, Joukkien hallinta, tarjoukset, ilmoitukset, väärinkäytösten esto ja audit-historia."],
      ["Oikeusperusteet", "Tilin, Joukkojen, tarjousten ja sopimusten toteuttaminen perustuu sopimukseen tai sitä edeltäviin toimiin; lakisääteinen kirjanpito ja viranomaisvelvoitteet lakisääteiseen velvoitteeseen; turvallisuus, väärinkäytösten esto ja palvelun kehittäminen punnittuun oikeutettuun etuun; ei-välttämättömät evästeet ja erikseen ilmoitetut toiminnot suostumukseen. Lopullinen käsittelytoimikohtainen arvio dokumentoidaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["AI:n käyttö", "AI voi auttaa jäsentelyssä ja vertailussa, mutta ei tee lopullista sitovaa päätöstä käyttäjän puolesta."],
      ["Vastaanottajat", "Yrityksille näytetään ennen hyväksyntää vain aggregoituja tietoja."],
      ["Palveluntoimittajat", "Tietoja voivat käsitellä ohjeidemme mukaisesti tunnistautumis-, tietokanta-, hosting-, ilmoitus- ja tarvittaessa AI-palveluiden toimittajat, kuten Supabase ja Render. Ajantasainen luettelo, roolit ja sopimukset vahvistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Hyväksyneiden tietojen luovutus", "Kun käyttäjä hyväksyy tietyn yrityksen tarjouksen, kaupan toteuttamiseen tarvittavat vähimmäistiedot voidaan luovuttaa kyseiselle yritykselle tallennetun suostumusversion ja tarkoituksen mukaisesti. LEGAL_REVIEW_REQUIRED"],
      ["Säilytysajat", "Tietoja säilytetään vain palvelun, sopimusten, reklamaatioiden, turvallisuuden ja lakisääteisten velvoitteiden vaatiman ajan. Tili- ja sisältötietojen, sopimus- ja laskutusaineiston, lokien sekä varmuuskopioiden tarkat poistosyklit vahvistetaan säilytysaikataulussa ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Tietojen siirrot", "EU- ja ETA-alueen ulkopuoliset käsittelijät ja siirtoperusteet tunnistetaan. Tarvittaessa käytetään tietosuojan riittävyyspäätöstä, vakiosopimuslausekkeita ja täydentäviä suojatoimia. Supabasen, Renderin ja AI-palvelun alueet tarkistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Käyttäjän oikeudet", "Rekisteröidyllä on tilanteen mukaan oikeus saada pääsy tietoihin, oikaista ja poistaa niitä, rajoittaa käsittelyä, vastustaa käsittelyä, siirtää tiedot järjestelmästä toiseen, peruuttaa suostumus sekä tehdä valitus toimivaltaiselle tietosuojaviranomaiselle."],
      ["Automaattinen päätöksenteko", "JOUKKO ei tee yksinomaan automaattiseen käsittelyyn perustuvia oikeusvaikutteisia tai vastaavasti merkittäviä päätöksiä käyttäjästä. Jos tämä muuttuu, logiikka, merkitys, seuraukset ja käyttäjän oikeudet ilmoitetaan etukäteen."],
      ["Tietoturva ja loukkaukset", "Tietoja suojataan käyttöoikeuksilla, lokituksella, salauksella, ympäristöjen erottelulla ja varmistuksilla. Loukkaukset arvioidaan, dokumentoidaan ja ilmoitetaan viranomaiselle ja rekisteröidylle lain edellyttämissä tilanteissa."],
      ["Lapset", "Palvelua ei suunnata lapsille sitovien kauppojen tekemiseen. Ikärajat ja huoltajan suostumuksen tarve määritetään ennen tuotantoa."],
      ["Poistopyynnöt", "Poistopyyntöjen vaikutus audit-historiaan määritetään juridisesti. LEGAL_REVIEW_REQUIRED"],
      ["Yhteystiedot", "Lisätään ennen tuotantojulkaisua."]
    ].map(([title, body]) => ({ title, body }))
  },
  tekoaly: {
    slug: "tekoaly",
    title: "Tekoälyn käyttö",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["Mihin tekoälyä voidaan käyttää", "Joukon ehdotuksen jäsentämiseen, samankaltaisten Joukkien tunnistamiseen, tarjousten vertailuun, kokonaishintojen analyysiin, piilokulujen havaitsemiseen ja yhteenvetoihin."],
      ["Taustapalvelu", "AI toimii palvelukerroksessa taustalla määritellyissä triggereissä. Käyttäjän ei tarvitse painaa erillistä AI-nappia."],
      ["Virhemahdollisuus", "Tekoäly voi tehdä virheitä."],
      ["Läpinäkyvyys", "Käyttäjälle kerrotaan viimeistään ensimmäisessä AI-avusteisessa vuorovaikutuksessa, kun hän asioi tekoälyn kanssa tai näkee AI:n tuottaman olennaisen yhteenvedon. Julkaistava synteettinen sisältö merkitään soveltuvan lain edellyttämällä tavalla."],
      ["Ihmisen valvonta", "Käyttäjä ja yritys tarkistavat AI:n yhteenvedot lähdetiedoista. Olennaiseen moderointi-, sopimus- tai oikeusvaikutteiseen ratkaisuun on saatavilla ihmisen arvio."],
      ["Tietojen minimointi", "AI:lle toimitetaan vain tehtävän kannalta tarpeelliset tiedot. Salaisuuksia, maksutietoja tai tarpeettomia henkilötietoja ei sisällytetä kehotteisiin, ja toimittajan säilytys- ja koulutuskäyttö tarkistetaan ennen tuotantoa."],
      ["Lokitus ja jäljitettävyys", "AI:n käyttö, malliversio, lähdeaineisto ja käyttäjälle näytetty tulos kirjataan riskin ja käyttötarkoituksen edellyttämällä tavalla ilman tarpeettomia henkilötietoja."],
      ["Myyjän ehdot", "AI ei keksi, muuta tai hyväksy myyjän myyntiehtoja. Yritys antaa tai hyväksyy ehdot itse."],
      ["Ei tekaistuja lukuja", "AI ei saa keksiä tarjouksia, hintoja, osallistujamääriä, alennuksia, yrityksiä tai sopimuksen syntymistä."],
      ["Päätöksenteko", "AI ei tee käyttäjän puolesta lopullista juridisesti sitovaa päätöstä."],
      ["Kustannusrajat ja fallback", "Jos AI on pois päältä, API-avain puuttuu tai kustannusraja täyttyy, JOUKKO jatkaa toimintaansa ilman AI-analyysiä."],
      ["Kaupalliset luvut", "Kaikki kaupalliset luvut tulevat oikeasta datasta."]
    ].map(([title, body]) => ({ title, body }))
  },
  evasteet: {
    slug: "evasteet",
    title: "Evästeet",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["MVP:n evästeet", "MVP ei lisää tarpeetonta käyttäjäseurantaa."],
      ["Välttämättömät teknologiat", "Kirjautuminen voi käyttää teknisesti välttämättömiä evästeitä Supabase Authin yhteydessä."],
      ["Evästeluettelo", "Ennen tuotantoa julkaistaan ajantasainen luettelo evästeen tai vastaavan teknologian nimestä, tarjoajasta, tarkoituksesta, tyypistä ja säilytysajasta. LEGAL_REVIEW_REQUIRED"],
      ["Analytiikka ja markkinointi", "Jos myöhemmin lisätään analytiikkaa tai markkinointiseurantaa, se estetään ennen vapaaehtoista suostumusta. Suostumuksen epääminen ei estä palvelun välttämättömiä toimintoja."],
      ["Valintojen muuttaminen", "Käyttäjä voi peruuttaa suostumuksen tai muuttaa evästevalintojaan yhtä helposti kuin antaa ne. Peruutus ei vaikuta sitä edeltäneen käsittelyn lainmukaisuuteen."],
      ["Selainasetukset", "Selain voi estää tai poistaa evästeitä, mutta välttämättömien kirjautumistietojen estäminen voi rajoittaa palvelun toimintaa."]
    ].map(([title, body]) => ({ title, body }))
  }
};
