import type { LegalDocument } from "./types";

export const legalDocuments: Record<LegalDocument["slug"], LegalDocument> = {
  kayttoehdot: {
    slug: "kayttoehdot",
    title: "Käyttöehdot",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["Palvelun tarkoitus", "JOUKKO kokoaa kuluttajien kiinnostusta, liittymisiä ja ehdollisia sitoumuksia ostovoimaksi."],
      ["Palveluntarjoaja", "Palveluntarjoajan viralliset tiedot lisätään ennen tuotantojulkaisua. LEGAL_REVIEW_REQUIRED"],
      ["Rekisteröityminen", "Käyttäjä luo tilin Supabase Auth -kirjautumisella. Rekisteröinnissä tallennetaan hyväksytty ehtoversio."],
      ["Käyttäjätili", "Käyttäjä vastaa antamiensa tietojen oikeellisuudesta."],
      ["Joukkoon liittyminen", "Liittyminen kasvattaa kiinnostuneiden määrää mutta ei yksin muodosta ostovelvoitetta."],
      ["Joukon perustaminen", "Aloittajan pitää kuvata tarve riittävän täsmällisesti. Olennaisia ehtoja ei saa muuttaa yksipuolisesti muiden liityttyä."],
      ["Ehdollinen sitoutuminen", "Käyttäjä voi sitoutua ehdoilla. Hyväksytyt ehdot tallennetaan muuttumattomana historiatietona."],
      ["Tarjousten hyväksyminen", "Käyttäjä hyväksyy tai hylkää tarjouksen aktiivisesti."],
      ["Ennakkotiedot ennen hyväksyntää", "Ennen sitovaa hyväksyntää näytetään myyjän tunnistetiedot, tarjouksen olennaiset ominaisuudet, kokonaishinta veroineen ja pakollisine kuluineen, toimitus- tai toteutustapa ja -aika, voimassaolo, kesto, irtisanomis- ja peruuttamisehdot sekä reklamaatio- ja virhevastuutiedot."],
      ["Maksuvelvollisuudesta kertova toiminto", "Jos hyväksyntä synnyttää maksuvelvollisuuden, painikkeen ja välittömän näkymän on ilmaistava se yksiselitteisesti. Pelkkää kiinnostuksen tai Minä myös -ilmaisua ei esitetä ostona."],
      ["Hyväksynnästä syntyvä deal", "Tarjouksen hyväksynnästä syntyy käyttäjäkohtainen deal, jolla on oma tila, toimitus-/toteutustieto ja historia."],
      ["Tietojen luovutus myyjälle", "Ennen hyväksyntää käyttäjälle näytetään, että kaupan toteuttamiseen tarvittavia vähimmäistietoja voidaan luovuttaa juuri kyseiselle yritykselle. Oikeusperuste ja tietoluokat tarkistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Toimitus ja toteutus", "Ennen hyväksyntää käyttäjälle näytetään tarjouksen päättymisaika ja myyjän ilmoittama arvioitu toimitus- tai toteutusaika."],
      ["Sopimuksen syntyminen", "Sopimuksen syntymisen tarkka hetki ja osapuolet vaativat juridisen tarkistuksen. LEGAL_REVIEW_REQUIRED"],
      ["Määräaikaiset sopimukset", "JOUKKO ei saa aiheuttaa sopimusrikettä käyttäjän puolesta."],
      ["Peruuttaminen ja kuluttajansuoja", "Kuluttajansuojan ja peruuttamisoikeuden yksityiskohdat tarkistetaan ennen julkaisua. LEGAL_REVIEW_REQUIRED"],
      ["Peruuttamistoiminto", "Kun lainsäädäntö sitä edellyttää, palvelussa tarjotaan helposti löydettävä sähköinen peruuttamistoiminto ja peruuttamisesta annetaan vahvistus pysyvällä tavalla. Myyjä ilmoittaa ennen sopimusta 14 päivän peruuttamisoikeuden tai soveltuvan lakisääteisen poikkeuksen ja sen perusteen. LEGAL_REVIEW_REQUIRED"],
      ["Tilaus- ja sopimusvahvistus", "Syntyneestä tilauksesta tai sopimuksesta toimitetaan käyttäjälle ilman aiheetonta viivytystä pysyvällä tavalla vahvistus, joka sisältää hyväksytyn tarjousversion, osapuolet, hinnan, ehdot ja toimitus- tai toteutustiedot."],
      ["Yrityksen ja kuluttajan välinen sopimus", "JOUKKO toimii alustana/välittäjänä määriteltävässä roolissa. LEGAL_REVIEW_REQUIRED"],
      ["Myyjän vastuu", "Myyjä määrittelee omat myyntiehtonsa ja vastaa tuotteesta, palvelusta, toimituksesta, reklamaatioista, takuista ja kuluttajansuojan pakollisista tiedoista oman roolinsa mukaisesti."],
      ["JOUKON asema", "Alustan asema välittäjänä tai markkinapaikkana täsmennetään juridisessa tarkistuksessa."],
      ["Kielletty käyttö", "Laiton sisältö, harhaanjohtavat tarjouspyynnöt ja henkilötietojen julkaisu julkiseen kuvaukseen on kielletty."],
      ["Sisällön moderointi", "Admin voi hyväksyä, piilottaa, keskeyttää tai jäädyttää Joukon."],
      ["Ilmoitus laittomasta sisällöstä ja muutoksenhaku", "Käyttäjälle tarjotaan yhteydenottokanava epäillyn laittoman tai ehtojen vastaisen sisällön ilmoittamiseen. Moderointipäätös perustellaan ja käytettävissä oleva oikaisu- tai valitusmenettely ilmoitetaan sovellettavan lain mukaan. LEGAL_REVIEW_REQUIRED"],
      ["Järjestys ja vertailu", "Vertailun ja tarjousten järjestämisen tärkeimmät perusteet, kuten kokonaishinta, ehdot, toimitusaika ja saavutettu hintaporras, kerrotaan käyttäjälle. Maksettu näkyvyys merkitään eikä sitä esitetä puolueettomana paremmuusjärjestyksenä."],
      ["Ikä ja oikeustoimikelpoisuus", "Sitovan hyväksynnän tekijällä on oltava siihen vaadittava oikeustoimikelpoisuus ja valtuus. Alaikäisiä tai säänneltyjä tuoteryhmiä koskevat rajat toteutetaan ennen niiden avaamista."],
      ["Vastuunrajoitukset", "Vastuunrajoitukset tehdään vain lain sallimissa rajoissa. LEGAL_REVIEW_REQUIRED"],
      ["Muutokset palveluun", "Palvelua voidaan kehittää ilman, että hyväksyttyä tarjoushistoriaa ylikirjoitetaan."],
      ["Ehtojen muutokset", "Uusi versio julkaistaan versionumerolla ja hyväksyntä tallennetaan tarvittaessa."],
      ["Sovellettava laki", "Sovellettava laki tarkennetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Yhteystiedot", "Yhteystiedot lisätään ennen tuotantojulkaisua."]
    ].map(([title, body]) => ({ title, body }))
  },
  yritysehdot: {
    slug: "yritysehdot",
    title: "Yritysehdot",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["Yritystilin avaaminen", "Yritys avaa tilin ja ilmoittaa perustiedot."],
      ["Varmentaminen", "Yrityksen henkilöllisyys ja edustusoikeus varmennetaan ennen oikeita kaupallisia tarjouksia."],
      ["Elinkeinonharjoittajan jäljitettävyys", "Yritys antaa ennen tarjoamista virallisen nimensä, osoitteensa, puhelinnumeronsa, sähköpostinsa, kauppa- tai muun rekisterin ja rekisterinumeron, soveltuvan tunnisteen, maksutilin tiedot sekä vakuutuksen EU-sääntöjen mukaisuudesta. JOUKKO voi estää tarjoamisen, kunnes tiedot on varmennettu. LEGAL_REVIEW_REQUIRED"],
      ["Tarjouksen tekeminen", "Tarjous sisältää tuotteen/palvelun, hinnan, pakolliset lisäkulut, toimituksen, minimimäärän ja ehdot."],
      ["Luonnoksen poistaminen", "Yritys voi poistaa kokonaan vain luonnoksen, jolla ei ole seuraajia, kiinnostuneita, hyväksyntöjä, dealeja tai muuta käyttäjäinteraktiota."],
      ["Hintaportaat", "Yritys voi määrittää useita portaita, jotka lukitaan saavutettaessa."],
      ["Voimassaolo ja sulkeutuminen", "Tarjouksella on voimassaoloaika, mahdollinen hyväksyjä-/kapasiteettiraja ja sulkeutumisen jälkeen jo hyväksyneet käsitellään loppuun."],
      ["Toimitus-/toteutusaika", "Yritys ilmoittaa milloin toimitus tai palvelu toteutetaan tarjouksen päättymisen jälkeen. Toimitusaika kuuluu lukittuihin tarjousversion olennaisiin ehtoihin."],
      ["Yrityksen sitoutuminen", "Julkaistu tarjousversio lukitsee olennaiset ehdot kuluttajien sitoumusten jälkeen."],
      ["Tarjouksen muuttaminen", "Olennaiset heikennykset tehdään uutena tarjousversiona, ei ylikirjoituksena."],
      ["Tarjousversiot", "Versio, julkaisuhetki, hinnat, ehdot ja hyväksynnät tallennetaan audit-historiaan."],
      ["Myyjän omat ehdot", "Yritys antaa ehdot tekstinä, linkkinä tai dokumenttiviitteenä. JOUKKO ei laadi lopullisia myyntiehtoja yrityksen puolesta."],
      ["Kuluttajan ennakkotiedot", "Yritys vastaa tavaran tai palvelun ominaisuuksien, kokonaishinnan, verojen, lisäkulujen, toimituksen, sopimuksen keston, päättämisen, peruuttamisoikeuden tai sen poikkeuksen, reklamaatiokanavan, lakisääteisen virhevastuun ja mahdollisen takuun oikeellisuudesta."],
      ["Tuoteturvallisuus ja takaisinvedot", "Yritys antaa soveltuvat valmistaja-, vastuuhenkilö-, tunniste-, varoitus- ja turvallisuustiedot, ylläpitää niitä sekä ilmoittaa viipymättä vaarasta, takaisinvedosta tai viranomaismääräyksestä. Säännelty tuoteryhmä voidaan estää ilman erillistä hyväksyntää."],
      ["Toteutuneet asiakkaat", "Yritys saa vain oman tarjouksensa hyväksyneiden kaupan toteuttamiseen tarvittavat vähimmäistiedot. Käsittely ja tietojen luovutus vaatii oikeusperusteen. LEGAL_REVIEW_REQUIRED"],
      ["Poikkeuskeskeytys", "Hyväksyntöjen jälkeen yritys ei voi yksipuolisesti perua tarjousta. Poikkeuskeskeytys vaatii perusteen, vaikutusten kuvauksen ja admin-tarkistuksen. LEGAL_REVIEW_REQUIRED"],
      ["Alustan palkkiot", "Ennen tarjouksen lähettämistä yritykselle näytetään valitun kategorian palkkioperuste, prosentti tai euromäärä, verokohtelu, laskentaesimerkki ja palkkion syntyhetki. Yritys hyväksyy täsmälleen tämän version. Completed deal synnyttää vain hyväksytyn version mukaisen palkkion."],
      ["Peruuttaminen ja vahvistukset", "Yritys toimittaa JOUKKOlle peruuttamisohjeet ja poikkeusperusteen sekä käsittelee sähköisen peruuttamisen. Tilaus-, sopimus- ja peruuttamisvahvistukset toimitetaan kuluttajalle pysyvällä tavalla lain edellyttämässä ajassa. LEGAL_REVIEW_REQUIRED"],
      ["Laskutus", "Commissionit voidaan koota viikko-, kuukausi- tai kampanjakohtaiseksi laskutukseksi. Live-Stripeä ei käytetä ilman erillistä hyväksyntää."],
      ["Kielletty toiminta", "Tekaistut tarjoukset, väärät hinnat ja harhaanjohtavat edut on kielletty."],
      ["Harhaanjohtavat hinnat", "Alennusprosentti vaatii luotettavan vertailuhinnan."],
      ["Keinotekoiset alennukset", "JOUKKO vertaa ensisijaisesti todellista kokonaishintaa."],
      ["Asiakastietojen käyttö", "Yritys ei näe yksittäisiä henkilötietoja ennen asianmukaista hyväksyntää ja saa käyttää tietoja vain sallittuun toteutustarkoitukseen."],
      ["Tietosuoja", "Yritys sitoutuu käsittelemään tietoja sovellettavan lain mukaan."],
      ["Tietojen käyttötarkoitus ja turvallisuus", "Yritys käyttää luovutettuja tietoja vain kyseisen kaupan toteuttamiseen, rajaa käyttöoikeudet, suojaa tiedot, ilmoittaa tietoturvaloukkauksista ja poistaa tai palauttaa tiedot, kun käsittelyperuste päättyy, jollei laki vaadi säilyttämistä."],
      ["Tarjousten keskeyttäminen", "Keskeytys säilyttää historian ja vaatii syyn."],
      ["Yritystilin jäädyttäminen", "Admin voi jäädyttää tilin väärinkäytöksissä."],
      ["Vastuut", "Vastuut täsmennetään juridisesti. LEGAL_REVIEW_REQUIRED"],
      ["Riidat ja laki", "Riidat ja sovellettava laki tarkistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"]
    ].map(([title, body]) => ({ title, body }))
  },
  tietosuoja: {
    slug: "tietosuoja",
    title: "Tietosuojaseloste",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["Rekisterinpitäjä", "Lisätään ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Kerättävät tiedot", "Tilitiedot, Joukkotiedot, sopimuksen päättymistiedot, postinumero, yritystiedot, tarjoushistoria, lokit ja tekniset tiedot."],
      ["Käsittelyn tarkoitus", "Palvelun tarjoaminen, Joukkien hallinta, tarjoukset, ilmoitukset, väärinkäytösten esto ja audit-historia."],
      ["Oikeusperusteet", "Tilin, Joukkojen, tarjousten ja sopimusten toteuttaminen perustuu sopimukseen tai sitä edeltäviin toimiin; lakisääteinen kirjanpito ja viranomaisvelvoitteet lakisääteiseen velvoitteeseen; turvallisuus, väärinkäytösten esto ja palvelun kehittäminen punnittuun oikeutettuun etuun; ei-välttämättömät evästeet ja erikseen ilmoitetut toiminnot suostumukseen. Lopullinen käsittelytoimikohtainen arvio dokumentoidaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["AI:n käyttö", "AI voi auttaa jäsentelyssä ja vertailussa, mutta ei tee lopullista sitovaa päätöstä käyttäjän puolesta."],
      ["Vastaanottajat", "Yrityksille näytetään ennen hyväksyntää vain aggregoituja tietoja."],
      ["Palveluntoimittajat", "Tietoja voivat käsitellä ohjeidemme mukaisesti tunnistautumis-, tietokanta-, hosting-, ilmoitus- ja tarvittaessa AI-palveluiden toimittajat, kuten Supabase ja Render. Ajantasainen luettelo, roolit ja sopimukset vahvistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Hyväksyneiden tietojen luovutus", "Kun käyttäjä hyväksyy tietyn yrityksen tarjouksen, kaupan toteuttamiseen tarvittavat vähimmäistiedot voidaan luovuttaa kyseiselle yritykselle tallennetun suostumusversion ja tarkoituksen mukaisesti. LEGAL_REVIEW_REQUIRED"],
      ["Säilytysajat", "Tietoja säilytetään vain palvelun, sopimusten, reklamaatioiden, turvallisuuden ja lakisääteisten velvoitteiden vaatiman ajan. Tili- ja sisältötietojen, sopimus- ja laskutusaineiston, lokien sekä varmuuskopioiden tarkat poistosyklit vahvistetaan säilytysaikataulussa ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Tietojen siirrot", "EU- ja ETA-alueen ulkopuoliset käsittelijät ja siirtoperusteet tunnistetaan. Tarvittaessa käytetään tietosuojan riittävyyspäätöstä, vakiosopimuslausekkeita ja täydentäviä suojatoimia. Supabasen, Renderin ja AI-palvelun alueet tarkistetaan ennen tuotantoa. LEGAL_REVIEW_REQUIRED"],
      ["Käyttäjän oikeudet", "Rekisteröidyllä on tilanteen mukaan oikeus saada pääsy tietoihin, oikaista ja poistaa niitä, rajoittaa käsittelyä, vastustaa käsittelyä, siirtää tiedot järjestelmästä toiseen, peruuttaa suostumus sekä tehdä valitus toimivaltaiselle tietosuojaviranomaiselle."],
      ["Automaattinen päätöksenteko", "JOUKKO ei tee yksinomaan automaattiseen käsittelyyn perustuvia oikeusvaikutteisia tai vastaavasti merkittäviä päätöksiä käyttäjästä. Jos tämä muuttuu, logiikka, merkitys, seuraukset ja käyttäjän oikeudet ilmoitetaan etukäteen."],
      ["Tietoturva ja loukkaukset", "Tietoja suojataan käyttöoikeuksilla, lokituksella, salauksella, ympäristöjen erottelulla ja varmistuksilla. Loukkaukset arvioidaan, dokumentoidaan ja ilmoitetaan viranomaiselle ja rekisteröidylle lain edellyttämissä tilanteissa."],
      ["Lapset", "Palvelua ei suunnata lapsille sitovien kauppojen tekemiseen. Ikärajat ja huoltajan suostumuksen tarve määritetään ennen tuotantoa."],
      ["Poistopyynnöt", "Poistopyyntöjen vaikutus audit-historiaan määritetään juridisesti. LEGAL_REVIEW_REQUIRED"],
      ["Yhteystiedot", "Lisätään ennen tuotantojulkaisua."]
    ].map(([title, body]) => ({ title, body }))
  },
  tekoaly: {
    slug: "tekoaly",
    title: "Tekoälyn käyttö",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["Mihin tekoälyä voidaan käyttää", "Joukon ehdotuksen jäsentämiseen, samankaltaisten Joukkien tunnistamiseen, tarjousten vertailuun, kokonaishintojen analyysiin, piilokulujen havaitsemiseen ja yhteenvetoihin."],
      ["Taustapalvelu", "AI toimii palvelukerroksessa taustalla määritellyissä triggereissä. Käyttäjän ei tarvitse painaa erillistä AI-nappia."],
      ["Virhemahdollisuus", "Tekoäly voi tehdä virheitä."],
      ["Läpinäkyvyys", "Käyttäjälle kerrotaan viimeistään ensimmäisessä AI-avusteisessa vuorovaikutuksessa, kun hän asioi tekoälyn kanssa tai näkee AI:n tuottaman olennaisen yhteenvedon. Julkaistava synteettinen sisältö merkitään soveltuvan lain edellyttämällä tavalla."],
      ["Ihmisen valvonta", "Käyttäjä ja yritys tarkistavat AI:n yhteenvedot lähdetiedoista. Olennaiseen moderointi-, sopimus- tai oikeusvaikutteiseen ratkaisuun on saatavilla ihmisen arvio."],
      ["Tietojen minimointi", "AI:lle toimitetaan vain tehtävän kannalta tarpeelliset tiedot. Salaisuuksia, maksutietoja tai tarpeettomia henkilötietoja ei sisällytetä kehotteisiin, ja toimittajan säilytys- ja koulutuskäyttö tarkistetaan ennen tuotantoa."],
      ["Lokitus ja jäljitettävyys", "AI:n käyttö, malliversio, lähdeaineisto ja käyttäjälle näytetty tulos kirjataan riskin ja käyttötarkoituksen edellyttämällä tavalla ilman tarpeettomia henkilötietoja."],
      ["Myyjän ehdot", "AI ei keksi, muuta tai hyväksy myyjän myyntiehtoja. Yritys antaa tai hyväksyy ehdot itse."],
      ["Ei tekaistuja lukuja", "AI ei saa keksiä tarjouksia, hintoja, osallistujamääriä, alennuksia, yrityksiä tai sopimuksen syntymistä."],
      ["Päätöksenteko", "AI ei tee käyttäjän puolesta lopullista juridisesti sitovaa päätöstä."],
      ["Kustannusrajat ja fallback", "Jos AI on pois päältä, API-avain puuttuu tai kustannusraja täyttyy, JOUKKO jatkaa toimintaansa ilman AI-analyysiä."],
      ["Kaupalliset luvut", "Kaikki kaupalliset luvut tulevat oikeasta datasta."]
    ].map(([title, body]) => ({ title, body }))
  },
  evasteet: {
    slug: "evasteet",
    title: "Evästeet",
    version: "0.2.0-draft",
    effectiveDate: "LEGAL_REVIEW_REQUIRED",
    updatedAt: "2026-08-31",
    sections: [
      ["MVP:n evästeet", "MVP ei lisää tarpeetonta käyttäjäseurantaa."],
      ["Välttämättömät teknologiat", "Kirjautuminen voi käyttää teknisesti välttämättömiä evästeitä Supabase Authin yhteydessä."],
      ["Evästeluettelo", "Ennen tuotantoa julkaistaan ajantasainen luettelo evästeen tai vastaavan teknologian nimestä, tarjoajasta, tarkoituksesta, tyypistä ja säilytysajasta. LEGAL_REVIEW_REQUIRED"],
      ["Analytiikka ja markkinointi", "Jos myöhemmin lisätään analytiikkaa tai markkinointiseurantaa, se estetään ennen vapaaehtoista suostumusta. Suostumuksen epääminen ei estä palvelun välttämättömiä toimintoja."],
      ["Valintojen muuttaminen", "Käyttäjä voi peruuttaa suostumuksen tai muuttaa evästevalintojaan yhtä helposti kuin antaa ne. Peruutus ei vaikuta sitä edeltäneen käsittelyn lainmukaisuuteen."],
      ["Selainasetukset", "Selain voi estää tai poistaa evästeitä, mutta välttämättömien kirjautumistietojen estäminen voi rajoittaa palvelun toimintaa."]
    ].map(([title, body]) => ({ title, body }))
  }
};
